/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wjx_android_ndksummary_MainActivity */

#ifndef _Included_com_wjx_android_ndksummary_MainActivity
#define _Included_com_wjx_android_ndksummary_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wjx_android_ndksummary_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wjx_android_ndksummary_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_wjx_android_ndksummary_MainActivity
 * Method:    myStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wjx_android_ndksummary_MainActivity_myStringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_wjx_android_ndksummary_MainActivity
 * Method:    myAddFromJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wjx_android_ndksummary_MainActivity_myAddFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
